### ISSUE TITLE
genericXMLmodule does not work for Pepper_2015.10.27-SNAPSHOT

### ISSUE THREAD

**Issue by CarolinOdebrecht** [korpling/pepperModules-GenericXMLModules#3]
The importer module does not work well for the Pepper_2015.10.27-SNAPSHOT (but for the stable version Pepper_2015.07.30. )
A first guess: the import of XML is inaccurat because pepper ignores the customizations during import process. (For example, the import of XML elements as spans for the relANNIS exporter).

The CARO.zip contains a corpus and the pepper workflow.
https://box.hu-berlin.de/d/07f610266d/

**Comment by FlorianZipser** [comment]
Can you please give me a more detailed description of the problem? How does the annis data should look like. I just tried the new snapshot version and the version of Pepper_2015.10.27-SNAPSHOT as well and the process looks good to me. Pepper displays the customizations as follows:

+----------------------------------- step 1 -----------------------------------+
|importer:      GenericXMLImporter                                             |
|path:          file:/home/florian/test/genericXMLProblem/CARO/CARO/Schoenberg |
|corpus index:  0                                                              |
|properties:                                                                   |
|               genericXml.importer.artificialSStruct:true                                  |
|               genericXml.importer.asSSpan://body//, //body, //p//, //p, //persName//, //persName, //label//, //label, //state//, //state|
|               genericXml.importer.elementNameAsSAnno://body//, //body, //p//, //p, //persName//, //persName, //label//, //label, //state//, //state|
|               genericXml.importer.file.endings:ALL                                   |
|               genericXml.importer.ignoreNamespaces:true                                  |
|               genericXml.importer.ignoreWhitepsaces:'
',' ',' '                       |
|               genericXml.importer.separateTokens:                                      |
|               genericXml.importer.textOnly:false                                 |
|               pepper.after.reportCorpusGraph:false                                 |
|                                                                              |
+----------------------------------- step 2 -----------------------------------+

But since I do not know, how the output should look like, I do not no where to keep an eye on. Maybe you can send an ANNIS screenshot?
